/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdDLingua;
import it.csi.sira.backend.metadata.integration.dao.MtdDLinguaDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * MtdDLingua DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdDLinguaDAOImpl extends GenericDAO<MtdDLingua> implements MtdDLinguaDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdDLinguaDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_d_language where id_language = :id_language";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_d_language(id_language,des_language) values(:id_language,:des_language)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_d_language set des_language = :des_language  where id_language = :id_language";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_d_language where  id_language = :id_language";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_d_language";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_d_language";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_d_language";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdDLingua findByPK(Integer idLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_language", idLingua);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_language", idLingua);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdDLingua MtdDLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_language", MtdDLingua.getIdLingua());
		map.put("des_language", MtdDLingua.getDesLingua());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdDLingua MtdDLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("des_language", MtdDLingua.getDesLingua());
		map.put("id_language", MtdDLingua.getIdLingua());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdDLingua MtdDLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_language", MtdDLingua.getIdLingua());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdDLingua MtdDLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_language", MtdDLingua.getIdLingua());
		return map;
	}

	@Override
	public RowMapper<MtdDLingua> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdDLinguaRowMapper( new MtdDLingua() ) ;

       return new MtdDLinguaRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdDLingua
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdDLingua MtdDLingua) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdDLingua.setIdLingua(rs.getInt("id_language")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdDLingua.setIdLingua(null); }; // not primitive number => keep null value if any
		MtdDLingua.setDesLingua(rs.getString("des_language")); // java.lang.String
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdDLinguaRowMapper implements RowMapper<MtdDLingua> {
	
		public MtdDLinguaRowMapper() {
			
		}
		
		public MtdDLingua mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdDLingua bean = new MtdDLingua();
			populateBean(rs, bean);
			return bean;
		}
	}
}
