/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdDStandardEspos;
import it.csi.sira.backend.metadata.integration.dao.MtdDStandardEsposDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * MtdDStandardEspos DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdDStandardEsposDAOImpl extends GenericDAO<MtdDStandardEspos> implements MtdDStandardEsposDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdDStandardEsposDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_d_standard_expos where id_standard_expos = :id_standard_expos";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_d_standard_expos(id_standard_expos,des_standard_expos) values(:id_standard_expos,:des_standard_expos)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_d_standard_expos set des_standard_expos = :des_standard_expos  where id_standard_expos = :id_standard_expos";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_d_standard_expos where  id_standard_expos = :id_standard_expos";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_d_standard_expos";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_d_standard_expos";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_d_standard_expos";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdDStandardEspos findByPK(Integer idStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_expos", idStandardEspos);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_expos", idStandardEspos);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdDStandardEspos MtdDStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_expos", MtdDStandardEspos.getIdStandardEspos());
		map.put("des_standard_expos", MtdDStandardEspos.getDesStandardEspos());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdDStandardEspos MtdDStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("des_standard_expos", MtdDStandardEspos.getDesStandardEspos());
		map.put("id_standard_expos", MtdDStandardEspos.getIdStandardEspos());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdDStandardEspos MtdDStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_expos", MtdDStandardEspos.getIdStandardEspos());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdDStandardEspos MtdDStandardEspos) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_standard_expos", MtdDStandardEspos.getIdStandardEspos());
		return map;
	}

	@Override
	public RowMapper<MtdDStandardEspos> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdDStandardEsposRowMapper( new MtdDStandardEspos() ) ;

       return new MtdDStandardEsposRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdDStandardEspos
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdDStandardEspos MtdDStandardEspos) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdDStandardEspos.setIdStandardEspos(rs.getInt("id_standard_expos")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdDStandardEspos.setIdStandardEspos(null); }; // not primitive number => keep null value if any
		MtdDStandardEspos.setDesStandardEspos(rs.getString("des_standard_expos")); // java.lang.String
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdDStandardEsposRowMapper implements RowMapper<MtdDStandardEspos> {
	
		public MtdDStandardEsposRowMapper() {
			
		}
		
		public MtdDStandardEspos mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdDStandardEspos bean = new MtdDStandardEspos();
			populateBean(rs, bean);
			return bean;
		}
	}
}
