/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdRCategoriaMtd;
import it.csi.sira.backend.metadata.integration.dao.MtdRCategoriaMtdDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * MtdRCategoriaMtd DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdRCategoriaMtdDAOImpl extends GenericDAO<MtdRCategoriaMtd> implements MtdRCategoriaMtdDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdRCategoriaMtdDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_r_category_mtd where id_category = :id_category and id_metadata = :id_metadata";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_r_category_mtd(id_category,id_metadata) values(:id_category,:id_metadata)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_r_category_mtd set   where id_category = :id_category and id_metadata = :id_metadata";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_r_category_mtd where  id_category = :id_category and id_metadata = :id_metadata";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_r_category_mtd";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_r_category_mtd";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_r_category_mtd";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdRCategoriaMtd findByPK(Integer idCategoria, Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", idCategoria);
		map.put("id_metadata", idMetadato);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idCategoria, Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", idCategoria);
		map.put("id_metadata", idMetadato);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdRCategoriaMtd MtdRCategoriaMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", MtdRCategoriaMtd.getIdCategoria());
		map.put("id_metadata", MtdRCategoriaMtd.getIdMetadato());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdRCategoriaMtd MtdRCategoriaMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", MtdRCategoriaMtd.getIdCategoria());
		map.put("id_metadata", MtdRCategoriaMtd.getIdMetadato());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdRCategoriaMtd MtdRCategoriaMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", MtdRCategoriaMtd.getIdCategoria());
		map.put("id_metadata", MtdRCategoriaMtd.getIdMetadato());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdRCategoriaMtd MtdRCategoriaMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", MtdRCategoriaMtd.getIdCategoria());
		map.put("id_metadata", MtdRCategoriaMtd.getIdMetadato());
		return map;
	}

	@Override
	public RowMapper<MtdRCategoriaMtd> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdRCategoriaMtdRowMapper( new MtdRCategoriaMtd() ) ;

       return new MtdRCategoriaMtdRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdRCategoriaMtd
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdRCategoriaMtd MtdRCategoriaMtd) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdRCategoriaMtd.setIdCategoria(rs.getInt("id_category")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdRCategoriaMtd.setIdCategoria(null); }; // not primitive number => keep null value if any
		MtdRCategoriaMtd.setIdMetadato(rs.getInt("id_metadata")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdRCategoriaMtd.setIdMetadato(null); }; // not primitive number => keep null value if any
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdRCategoriaMtdRowMapper implements RowMapper<MtdRCategoriaMtd> {
	
		public MtdRCategoriaMtdRowMapper() {
			
		}
		
		public MtdRCategoriaMtd mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdRCategoriaMtd bean = new MtdRCategoriaMtd();
			populateBean(rs, bean);
			return bean;
		}
	}
}
