/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdRCategLingua;
import it.csi.sira.backend.metadata.integration.dao.MtdRCategLinguaDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * MtdRCategLingua DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdRCategLinguaDAOImpl extends GenericDAO<MtdRCategLingua> implements MtdRCategLinguaDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdRCategLinguaDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_r_categ_language where id_category = :id_category and id_language = :id_language";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_r_categ_language(id_category,id_language,des_category,des_alias,fl_alias) values(:id_category,:id_language,:des_category,:des_alias,:fl_alias)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_r_categ_language set des_category = :des_category, des_alias = :des_alias, fl_alias = :fl_alias  where id_category = :id_category and id_language = :id_language";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_r_categ_language where  id_category = :id_category and id_language = :id_language";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_r_categ_language";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_r_categ_language";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_r_categ_language";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdRCategLingua findByPK(Integer idCategoria, Integer idLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", idCategoria);
		map.put("id_language", idLingua);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idCategoria, Integer idLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", idCategoria);
		map.put("id_language", idLingua);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdRCategLingua MtdRCategLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", MtdRCategLingua.getIdCategoria());
		map.put("id_language", MtdRCategLingua.getIdLingua());
		map.put("des_category", MtdRCategLingua.getDesCategoria());
		map.put("des_alias", MtdRCategLingua.getDesAlias());
		map.put("fl_alias", MtdRCategLingua.getFlAlias());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdRCategLingua MtdRCategLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("des_category", MtdRCategLingua.getDesCategoria());
		map.put("des_alias", MtdRCategLingua.getDesAlias());
		map.put("fl_alias", MtdRCategLingua.getFlAlias());
		map.put("id_category", MtdRCategLingua.getIdCategoria());
		map.put("id_language", MtdRCategLingua.getIdLingua());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdRCategLingua MtdRCategLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", MtdRCategLingua.getIdCategoria());
		map.put("id_language", MtdRCategLingua.getIdLingua());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdRCategLingua MtdRCategLingua) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_category", MtdRCategLingua.getIdCategoria());
		map.put("id_language", MtdRCategLingua.getIdLingua());
		return map;
	}

	@Override
	public RowMapper<MtdRCategLingua> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdRCategLinguaRowMapper( new MtdRCategLingua() ) ;

       return new MtdRCategLinguaRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdRCategLingua
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdRCategLingua MtdRCategLingua) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdRCategLingua.setIdCategoria(rs.getInt("id_category")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdRCategLingua.setIdCategoria(null); }; // not primitive number => keep null value if any
		MtdRCategLingua.setIdLingua(rs.getInt("id_language")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdRCategLingua.setIdLingua(null); }; // not primitive number => keep null value if any
		MtdRCategLingua.setDesCategoria(rs.getString("des_category")); // java.lang.String
		MtdRCategLingua.setDesAlias(rs.getString("des_alias")); // java.lang.String
		MtdRCategLingua.setFlAlias(rs.getString("fl_alias")); // java.lang.String
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdRCategLinguaRowMapper implements RowMapper<MtdRCategLingua> {
	
		public MtdRCategLinguaRowMapper() {
			
		}
		
		public MtdRCategLingua mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdRCategLingua bean = new MtdRCategLingua();
			populateBean(rs, bean);
			return bean;
		}
	}
}
