/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdRParolachiaveMtd;
import it.csi.sira.backend.metadata.integration.dao.MtdRParolachiaveMtdDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * MtdRParolachiaveMtd DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdRParolachiaveMtdDAOImpl extends GenericDAO<MtdRParolachiaveMtd> implements MtdRParolachiaveMtdDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdRParolachiaveMtdDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_r_keyword_mtd where id_metadata = :id_metadata and id_keyword = :id_keyword";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_r_keyword_mtd(id_metadata,id_keyword) values(:id_metadata,:id_keyword)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_r_keyword_mtd set   where id_metadata = :id_metadata and id_keyword = :id_keyword";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_r_keyword_mtd where  id_metadata = :id_metadata and id_keyword = :id_keyword";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_r_keyword_mtd";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_r_keyword_mtd";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_r_keyword_mtd";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdRParolachiaveMtd findByPK(Integer idMetadato, Integer idParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", idMetadato);
		map.put("id_keyword", idParolaChiave);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idMetadato, Integer idParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", idMetadato);
		map.put("id_keyword", idParolaChiave);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdRParolachiaveMtd MtdRParolachiaveMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", MtdRParolachiaveMtd.getIdMetadato());
		map.put("id_keyword", MtdRParolachiaveMtd.getIdParolaChiave());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdRParolachiaveMtd MtdRParolachiaveMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", MtdRParolachiaveMtd.getIdMetadato());
		map.put("id_keyword", MtdRParolachiaveMtd.getIdParolaChiave());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdRParolachiaveMtd MtdRParolachiaveMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", MtdRParolachiaveMtd.getIdMetadato());
		map.put("id_keyword", MtdRParolachiaveMtd.getIdParolaChiave());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdRParolachiaveMtd MtdRParolachiaveMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", MtdRParolachiaveMtd.getIdMetadato());
		map.put("id_keyword", MtdRParolachiaveMtd.getIdParolaChiave());
		return map;
	}

	@Override
	public RowMapper<MtdRParolachiaveMtd> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdRParolachiaveMtdRowMapper( new MtdRParolachiaveMtd() ) ;

       return new MtdRParolachiaveMtdRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdRParolachiaveMtd
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdRParolachiaveMtd MtdRParolachiaveMtd) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdRParolachiaveMtd.setIdMetadato(rs.getInt("id_metadata")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdRParolachiaveMtd.setIdMetadato(null); }; // not primitive number => keep null value if any
		MtdRParolachiaveMtd.setIdParolaChiave(rs.getInt("id_keyword")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdRParolachiaveMtd.setIdParolaChiave(null); }; // not primitive number => keep null value if any
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdRParolachiaveMtdRowMapper implements RowMapper<MtdRParolachiaveMtd> {
	
		public MtdRParolachiaveMtdRowMapper() {
			
		}
		
		public MtdRParolachiaveMtd mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdRParolachiaveMtd bean = new MtdRParolachiaveMtd();
			populateBean(rs, bean);
			return bean;
		}
	}
}
