/*
 * Created on 18 nov 2016 ( Time 17:08:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdTStoricoFunzione;
import it.csi.sira.backend.metadata.integration.dao.MtdTStoricoFunzioneDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * MtdTStoricoFunzione DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdTStoricoFunzioneDAOImpl extends GenericDAO<MtdTStoricoFunzione> implements MtdTStoricoFunzioneDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdTStoricoFunzioneDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_t_function_history where id_function_history = :id_function_history";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_t_function_history(fk_function_type,id_function_history,request_url,fk_metadata) values(:fk_function_type,:id_function_history,:request_url,:fk_metadata)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_t_function_history set fk_function_type = :fk_function_type, request_url = :request_url, fk_metadata = :fk_metadata  where id_function_history = :id_function_history";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_t_function_history where  id_function_history = :id_function_history";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_t_function_history";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_t_function_history";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_t_function_history";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdTStoricoFunzione findByPK(Integer idStoricoFunzione) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_function_history", idStoricoFunzione);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idStoricoFunzione) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_function_history", idStoricoFunzione);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdTStoricoFunzione MtdTStoricoFunzione) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("fk_function_type", MtdTStoricoFunzione.getFkTipoFunzione());
		map.put("id_function_history", MtdTStoricoFunzione.getIdStoricoFunzione());
		map.put("request_url", MtdTStoricoFunzione.getRequestUrl());
		map.put("fk_metadata", MtdTStoricoFunzione.getFkMetadato());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdTStoricoFunzione MtdTStoricoFunzione) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("fk_function_type", MtdTStoricoFunzione.getFkTipoFunzione());
		map.put("request_url", MtdTStoricoFunzione.getRequestUrl());
		map.put("fk_metadata", MtdTStoricoFunzione.getFkMetadato());
		map.put("id_function_history", MtdTStoricoFunzione.getIdStoricoFunzione());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdTStoricoFunzione MtdTStoricoFunzione) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_function_history", MtdTStoricoFunzione.getIdStoricoFunzione());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdTStoricoFunzione MtdTStoricoFunzione) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_function_history", MtdTStoricoFunzione.getIdStoricoFunzione());
		return map;
	}

	@Override
	public RowMapper<MtdTStoricoFunzione> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdTStoricoFunzioneRowMapper( new MtdTStoricoFunzione() ) ;

       return new MtdTStoricoFunzioneRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdTStoricoFunzione
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdTStoricoFunzione MtdTStoricoFunzione) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdTStoricoFunzione.setFkTipoFunzione(rs.getInt("fk_function_type")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTStoricoFunzione.setFkTipoFunzione(null); }; // not primitive number => keep null value if any
		MtdTStoricoFunzione.setIdStoricoFunzione(rs.getInt("id_function_history")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTStoricoFunzione.setIdStoricoFunzione(null); }; // not primitive number => keep null value if any
		MtdTStoricoFunzione.setRequestUrl(rs.getString("request_url")); // java.lang.String
		MtdTStoricoFunzione.setFkMetadato(rs.getInt("fk_metadata")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTStoricoFunzione.setFkMetadato(null); }; // not primitive number => keep null value if any
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdTStoricoFunzioneRowMapper implements RowMapper<MtdTStoricoFunzione> {
	
		public MtdTStoricoFunzioneRowMapper() {
			
		}
		
		public MtdTStoricoFunzione mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdTStoricoFunzione bean = new MtdTStoricoFunzione();
			populateBean(rs, bean);
			return bean;
		}
	}
}
