/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdTDettlog;
import it.csi.sira.backend.metadata.integration.dao.MtdTDettlogDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * MtdTDettlog DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdTDettlogDAOImpl extends GenericDAO<MtdTDettlog> implements MtdTDettlogDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdTDettlogDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_t_detlog where id_det_log = :id_det_log";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_t_detlog(id_det_log,fk_log,cod_error) values(:id_det_log,:fk_log,:cod_error)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_t_detlog set fk_log = :fk_log, cod_error = :cod_error  where id_det_log = :id_det_log";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_t_detlog where  id_det_log = :id_det_log";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_t_detlog";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_t_detlog";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_t_detlog";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdTDettlog findByPK(Integer idDettLog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_det_log", idDettLog);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idDettLog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_det_log", idDettLog);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdTDettlog MtdTDettlog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_det_log", MtdTDettlog.getIdDettLog());
		map.put("fk_log", MtdTDettlog.getFkLog());
		map.put("cod_error", MtdTDettlog.getCodErrore());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdTDettlog MtdTDettlog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("fk_log", MtdTDettlog.getFkLog());
		map.put("cod_error", MtdTDettlog.getCodErrore());
		map.put("id_det_log", MtdTDettlog.getIdDettLog());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdTDettlog MtdTDettlog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_det_log", MtdTDettlog.getIdDettLog());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdTDettlog MtdTDettlog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_det_log", MtdTDettlog.getIdDettLog());
		return map;
	}

	@Override
	public RowMapper<MtdTDettlog> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdTDettlogRowMapper( new MtdTDettlog() ) ;

       return new MtdTDettlogRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdTDettlog
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdTDettlog MtdTDettlog) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdTDettlog.setIdDettLog(rs.getInt("id_det_log")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTDettlog.setIdDettLog(null); }; // not primitive number => keep null value if any
		MtdTDettlog.setFkLog(rs.getInt("fk_log")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTDettlog.setFkLog(null); }; // not primitive number => keep null value if any
		MtdTDettlog.setCodErrore(rs.getString("cod_error")); // java.lang.String
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdTDettlogRowMapper implements RowMapper<MtdTDettlog> {
	
		public MtdTDettlogRowMapper() {
			
		}
		
		public MtdTDettlog mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdTDettlog bean = new MtdTDettlog();
			populateBean(rs, bean);
			return bean;
		}
	}
}
