/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdTLog;
import it.csi.sira.backend.metadata.integration.dao.MtdTLogDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;
import java.util.Date;

/**
 * MtdTLog DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdTLogDAOImpl extends GenericDAO<MtdTLog> implements MtdTLogDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdTLogDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_t_log where id_log = :id_log";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_t_log(id_log,des_log,data_log) values(:id_log,:des_log,:data_log)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_t_log set des_log = :des_log, data_log = :data_log  where id_log = :id_log";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_t_log where  id_log = :id_log";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_t_log";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_t_log";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_t_log";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdTLog findByPK(Integer idLog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_log", idLog);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idLog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_log", idLog);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdTLog MtdTLog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_log", MtdTLog.getIdLog());
		map.put("des_log", MtdTLog.getDesLog());
		map.put("data_log", MtdTLog.getDataLog());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdTLog MtdTLog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("des_log", MtdTLog.getDesLog());
		map.put("data_log", MtdTLog.getDataLog());
		map.put("id_log", MtdTLog.getIdLog());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdTLog MtdTLog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_log", MtdTLog.getIdLog());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdTLog MtdTLog) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_log", MtdTLog.getIdLog());
		return map;
	}

	@Override
	public RowMapper<MtdTLog> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdTLogRowMapper( new MtdTLog() ) ;

       return new MtdTLogRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdTLog
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdTLog MtdTLog) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdTLog.setIdLog(rs.getInt("id_log")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTLog.setIdLog(null); }; // not primitive number => keep null value if any
		MtdTLog.setDesLog(rs.getString("des_log")); // java.lang.String
		MtdTLog.setDataLog(rs.getDate("data_log")); // java.util.Date
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdTLogRowMapper implements RowMapper<MtdTLog> {
	
		public MtdTLogRowMapper() {
			
		}
		
		public MtdTLog mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdTLog bean = new MtdTLog();
			populateBean(rs, bean);
			return bean;
		}
	}
}
