/*
 * Created on 18 nov 2016 ( Time 17:08:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdTMtdPlus;
import it.csi.sira.backend.metadata.integration.dao.MtdTMtdPlusDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * MtdTMtdPlus DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdTMtdPlusDAOImpl extends GenericDAO<MtdTMtdPlus> implements MtdTMtdPlusDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdTMtdPlusDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_t_mtd_plus where id_metadata = :id_metadata";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_t_mtd_plus(id_metadata,object_num_dataset_calc,fk_object_type) values(:id_metadata,:object_num_dataset_calc,:fk_object_type)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_t_mtd_plus set object_num_dataset_calc = :object_num_dataset_calc, fk_object_type = :fk_object_type  where id_metadata = :id_metadata";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_t_mtd_plus where  id_metadata = :id_metadata";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_t_mtd_plus";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_t_mtd_plus";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_t_mtd_plus";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdTMtdPlus findByPK(Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", idMetadato);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idMetadato) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", idMetadato);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdTMtdPlus MtdTMtdPlus) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", MtdTMtdPlus.getIdMetadato());
		map.put("object_num_dataset_calc", MtdTMtdPlus.getNrOggettiDatasetCalc());
		map.put("fk_object_type", MtdTMtdPlus.getFkTipoOggetto());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdTMtdPlus MtdTMtdPlus) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("object_num_dataset_calc", MtdTMtdPlus.getNrOggettiDatasetCalc());
		map.put("fk_object_type", MtdTMtdPlus.getFkTipoOggetto());
		map.put("id_metadata", MtdTMtdPlus.getIdMetadato());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdTMtdPlus MtdTMtdPlus) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", MtdTMtdPlus.getIdMetadato());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdTMtdPlus MtdTMtdPlus) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", MtdTMtdPlus.getIdMetadato());
		return map;
	}

	@Override
	public RowMapper<MtdTMtdPlus> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdTMtdPlusRowMapper( new MtdTMtdPlus() ) ;

       return new MtdTMtdPlusRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdTMtdPlus
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdTMtdPlus MtdTMtdPlus) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdTMtdPlus.setIdMetadato(rs.getInt("id_metadata")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTMtdPlus.setIdMetadato(null); }; // not primitive number => keep null value if any
		MtdTMtdPlus.setNrOggettiDatasetCalc(rs.getInt("object_num_dataset_calc")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTMtdPlus.setNrOggettiDatasetCalc(null); }; // not primitive number => keep null value if any
		MtdTMtdPlus.setFkTipoOggetto(rs.getInt("fk_object_type")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTMtdPlus.setFkTipoOggetto(null); }; // not primitive number => keep null value if any
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdTMtdPlusRowMapper implements RowMapper<MtdTMtdPlus> {
	
		public MtdTMtdPlusRowMapper() {
			
		}
		
		public MtdTMtdPlus mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdTMtdPlus bean = new MtdTMtdPlus();
			populateBean(rs, bean);
			return bean;
		}
	}
}
