/*
 * Created on 18 nov 2016 ( Time 17:08:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.MtdTParolaChiave;
import it.csi.sira.backend.metadata.integration.dao.MtdTParolaChiaveDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * MtdTParolaChiave DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class MtdTParolaChiaveDAOImpl extends GenericDAO<MtdTParolaChiave> implements MtdTParolaChiaveDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public MtdTParolaChiaveDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_t_keyword where id_keyword = :id_keyword";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_t_keyword(id_keyword,des_keyword) values(:id_keyword,:des_keyword)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_t_keyword set des_keyword = :des_keyword  where id_keyword = :id_keyword";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_t_keyword where  id_keyword = :id_keyword";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_t_keyword";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_t_keyword";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_t_keyword";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public MtdTParolaChiave findByPK(Integer idParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_keyword", idParolaChiave);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_keyword", idParolaChiave);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(MtdTParolaChiave MtdTParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_keyword", MtdTParolaChiave.getIdParolaChiave());
		map.put("des_keyword", MtdTParolaChiave.getDesParolaChiave());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(MtdTParolaChiave MtdTParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("des_keyword", MtdTParolaChiave.getDesParolaChiave());
		map.put("id_keyword", MtdTParolaChiave.getIdParolaChiave());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(MtdTParolaChiave MtdTParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_keyword", MtdTParolaChiave.getIdParolaChiave());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(MtdTParolaChiave MtdTParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_keyword", MtdTParolaChiave.getIdParolaChiave());
		return map;
	}

	@Override
	public RowMapper<MtdTParolaChiave> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new MtdTParolaChiaveRowMapper( new MtdTParolaChiave() ) ;

       return new MtdTParolaChiaveRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param MtdTParolaChiave
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, MtdTParolaChiave MtdTParolaChiave) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		MtdTParolaChiave.setIdParolaChiave(rs.getInt("id_keyword")); // java.lang.Integer
		if ( rs.wasNull() ) { MtdTParolaChiave.setIdParolaChiave(null); }; // not primitive number => keep null value if any
		MtdTParolaChiave.setDesParolaChiave(rs.getString("des_keyword")); // java.lang.String
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class MtdTParolaChiaveRowMapper implements RowMapper<MtdTParolaChiave> {
	
		public MtdTParolaChiaveRowMapper() {
			
		}
		
		public MtdTParolaChiave mapRow(ResultSet rs, int rowNum) throws SQLException {
			MtdTParolaChiave bean = new MtdTParolaChiave();
			populateBean(rs, bean);
			return bean;
		}
	}
}
