/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdRParolachiaveMtd;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdRParolachiaveMtdDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * SipraMtdRParolachiaveMtd DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdRParolachiaveMtdDAOImpl extends GenericDAO<SipraMtdRParolachiaveMtd> implements SipraMtdRParolachiaveMtdDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdRParolachiaveMtdDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from sipra_mtd_r_parolachiave_mtd where id_metadata = :id_metadata and id_keyword = :id_keyword";
	
	private final static String QUERY_INSERT = 
		"insert into sipra_mtd_r_parolachiave_mtd(id_metadata,id_keyword) values(:id_metadata,:id_keyword)";

	private final static String QUERY_UPDATE = 
		"update sipra_mtd_r_parolachiave_mtd set   where id_metadata = :id_metadata and id_keyword = :id_keyword";

	private final static String QUERY_DELETE = 
		"delete from sipra_mtd_r_parolachiave_mtd where  id_metadata = :id_metadata and id_keyword = :id_keyword";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from sipra_mtd_r_parolachiave_mtd";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "sipra_mtd_r_parolachiave_mtd";
	}

	@Override
	public String getSqlSelect() {
		return "select * from sipra_mtd_r_parolachiave_mtd";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdRParolachiaveMtd findByPK(Integer idMetadato, Integer idParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", idMetadato);
		map.put("id_keyword", idParolaChiave);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idMetadato, Integer idParolaChiave) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", idMetadato);
		map.put("id_keyword", idParolaChiave);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdRParolachiaveMtd sipraMtdRParolachiaveMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", sipraMtdRParolachiaveMtd.getIdMetadato());
		map.put("id_keyword", sipraMtdRParolachiaveMtd.getIdParolaChiave());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdRParolachiaveMtd sipraMtdRParolachiaveMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", sipraMtdRParolachiaveMtd.getIdMetadato());
		map.put("id_keyword", sipraMtdRParolachiaveMtd.getIdParolaChiave());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdRParolachiaveMtd sipraMtdRParolachiaveMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", sipraMtdRParolachiaveMtd.getIdMetadato());
		map.put("id_keyword", sipraMtdRParolachiaveMtd.getIdParolaChiave());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdRParolachiaveMtd sipraMtdRParolachiaveMtd) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_metadata", sipraMtdRParolachiaveMtd.getIdMetadato());
		map.put("id_keyword", sipraMtdRParolachiaveMtd.getIdParolaChiave());
		return map;
	}

	@Override
	public RowMapper<SipraMtdRParolachiaveMtd> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdRParolachiaveMtdRowMapper( new SipraMtdRParolachiaveMtd() ) ;

       return new SipraMtdRParolachiaveMtdRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdRParolachiaveMtd
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdRParolachiaveMtd sipraMtdRParolachiaveMtd) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdRParolachiaveMtd.setIdMetadato(rs.getInt("id_metadata")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdRParolachiaveMtd.setIdMetadato(null); }; // not primitive number => keep null value if any
		sipraMtdRParolachiaveMtd.setIdParolaChiave(rs.getInt("id_keyword")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdRParolachiaveMtd.setIdParolaChiave(null); }; // not primitive number => keep null value if any
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdRParolachiaveMtdRowMapper implements RowMapper<SipraMtdRParolachiaveMtd> {
	
		public SipraMtdRParolachiaveMtdRowMapper() {
			
		}
		
		public SipraMtdRParolachiaveMtd mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdRParolachiaveMtd bean = new SipraMtdRParolachiaveMtd();
			populateBean(rs, bean);
			return bean;
		}
	}
}
