/*
 * Created on 25 nov 2016 ( Time 10:35:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;

import it.csi.sira.backend.metadata.integration.dto.SipraMtdDFontedati;
import it.csi.sira.backend.metadata.integration.dao.SipraMtdDFontedatiDAO;
import it.csi.sira.backend.metadata.utils.GenericDAO;
import org.springframework.jdbc.core.RowMapper;

/**
 * SipraMtdDFontedati DAO implementation 
 * 
 * @author Telosys Tools
 *
 */
public class SipraMtdDFontedatiDAOImpl extends GenericDAO<SipraMtdDFontedati> implements SipraMtdDFontedatiDAO {
	//----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public SipraMtdDFontedatiDAOImpl() {
		super();
	}

	private final static String QUERY_PRIMARY_KEY = 
		"select * from bifisic_mtd_d_datasource where id_datasource = :id_datasource";
	
	private final static String QUERY_INSERT = 
		"insert into bifisic_mtd_d_datasource(id_datasource,fk_standard_expos,des_datasource,url_prefix_metadata,url_service,fl_active,prefix_datasource) values(:id_datasource,:fk_standard_expos,:des_datasource,:url_prefix_metadata,:url_service,:fl_active,:prefix_datasource)";

	private final static String QUERY_UPDATE = 
		"update bifisic_mtd_d_datasource set fk_standard_expos = :fk_standard_expos, des_datasource = :des_datasource, url_prefix_metadata = :url_prefix_metadata, url_service = :url_service, fl_active = :fl_active, prefix_datasource = :prefix_datasource  where id_datasource = :id_datasource";

	private final static String QUERY_DELETE = 
		"delete from bifisic_mtd_d_datasource where  id_datasource = :id_datasource";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from bifisic_mtd_d_datasource";
	
	@Override
	public String getPrimaryKeySelect() {
		return QUERY_PRIMARY_KEY;		
	}
	
	@Override
	public String getTableName(){
		return "bifisic_mtd_d_datasource";
	}

	@Override
	public String getSqlSelect() {
		return "select * from bifisic_mtd_d_datasource";
	}

	@Override
	public String getSqlInsert() {
		return QUERY_INSERT;
	}

	@Override
	public String getSqlUpdate() {
		return QUERY_UPDATE;
	}

	@Override
	public String getSqlDelete() {
		return QUERY_DELETE;
	}

	@Override
	public String getSqlCount() {
		return SQL_COUNT_ALL;
	}

	public SipraMtdDFontedati findByPK(Integer idFontedati) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_datasource", idFontedati);
		return super.findByPK(map);		
	}

	public int deleteByPK(Integer idFontedati) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_datasource", idFontedati);
		return super.delete(getSqlDelete(), map);		
	}

	@Override
	public java.util.Map<String, Object> getValuesForInsert(SipraMtdDFontedati sipraMtdDFontedati) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_datasource", sipraMtdDFontedati.getIdFontedati());
		map.put("fk_standard_expos", sipraMtdDFontedati.getFkStandardEspos());
		map.put("des_datasource", sipraMtdDFontedati.getDesFontedati());
		map.put("url_prefix_metadata", sipraMtdDFontedati.getUrlPrefissoMetadato());
		map.put("url_service", sipraMtdDFontedati.getUrlServizio());
		map.put("fl_active", sipraMtdDFontedati.getFlAttiva());
		map.put("prefix_datasource", sipraMtdDFontedati.getPrefissoFontedati());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForUpdate(SipraMtdDFontedati sipraMtdDFontedati) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("fk_standard_expos", sipraMtdDFontedati.getFkStandardEspos());
		map.put("des_datasource", sipraMtdDFontedati.getDesFontedati());
		map.put("url_prefix_metadata", sipraMtdDFontedati.getUrlPrefissoMetadato());
		map.put("url_service", sipraMtdDFontedati.getUrlServizio());
		map.put("fl_active", sipraMtdDFontedati.getFlAttiva());
		map.put("prefix_datasource", sipraMtdDFontedati.getPrefissoFontedati());
		map.put("id_datasource", sipraMtdDFontedati.getIdFontedati());
		return map;
	}

	public java.util.Map<String, Object> getValuesForPrimaryKey(SipraMtdDFontedati sipraMtdDFontedati) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_datasource", sipraMtdDFontedati.getIdFontedati());
		return map;
	}

	@Override
	public java.util.Map<String, Object> getValuesForDelete(SipraMtdDFontedati sipraMtdDFontedati) {
		java.util.Map<String, Object> map = new java.util.HashMap<String, Object>();
		map.put("id_datasource", sipraMtdDFontedati.getIdFontedati());
		return map;
	}

	@Override
	public RowMapper<SipraMtdDFontedati> getRowMapper()  {
		//--- RowMapper to populate a new bean instance
		//return new SipraMtdDFontedatiRowMapper( new SipraMtdDFontedati() ) ;

       return new SipraMtdDFontedatiRowMapper() ;
	}

	//----------------------------------------------------------------------
	/**
	 * Populates the given bean with the data retrieved from the given ResultSet
	 * @param rs
	 * @param sipraMtdDFontedati
	 * @throws SQLException
	 */
	private static void populateBean(ResultSet rs, SipraMtdDFontedati sipraMtdDFontedati) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		sipraMtdDFontedati.setIdFontedati(rs.getInt("id_datasource")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdDFontedati.setIdFontedati(null); }; // not primitive number => keep null value if any
		sipraMtdDFontedati.setFkStandardEspos(rs.getInt("fk_standard_expos")); // java.lang.Integer
		if ( rs.wasNull() ) { sipraMtdDFontedati.setFkStandardEspos(null); }; // not primitive number => keep null value if any
		sipraMtdDFontedati.setDesFontedati(rs.getString("des_datasource")); // java.lan	.String
		sipraMtdDFontedati.setUrlPrefissoMetadato(rs.getString("url_prefix_metadata")); // java.lang.String
		sipraMtdDFontedati.setUrlServizio(rs.getString("url_service")); // java.lang.String
		sipraMtdDFontedati.setFlAttiva(rs.getString("fl_active")); // java.lang.String
		sipraMtdDFontedati.setPrefissoFontedati(rs.getString("prefix_datasource")); // java.lang.String
	}


	/**
	 * Specific inner class for 'RowMapper' implementation
	 */
	public static class SipraMtdDFontedatiRowMapper implements RowMapper<SipraMtdDFontedati> {
	
		public SipraMtdDFontedatiRowMapper() {
			
		}
		
		public SipraMtdDFontedati mapRow(ResultSet rs, int rowNum) throws SQLException {
			SipraMtdDFontedati bean = new SipraMtdDFontedati();
			populateBean(rs, bean);
			return bean;
		}
	}
}
