/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.MtdDLingua;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * MtdDLingua DAO interface
 * 
 * @author Telosys Tools
 */
public interface MtdDLinguaDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idLingua
	 * @return the bean found or null if not found 
	 */
	public MtdDLingua findByPK(Integer idLingua);

	public List<MtdDLingua> findAll();
	
	public List<MtdDLingua> findByCriteria(java.util.Map<String, Object> params);
	public List<MtdDLingua> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<MtdDLingua> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(MtdDLingua bean);

	public void update(MtdDLingua bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idLingua);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<MtdDLingua> getRowMapper();
}
