/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.MtdDFontedati;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * MtdDFontedati DAO interface
 * 
 * @author Telosys Tools
 */
public interface MtdDFontedatiDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idFontedati
	 * @return the bean found or null if not found 
	 */
	public MtdDFontedati findByPK(Integer idFontedati);

	public List<MtdDFontedati> findAll();
	
	public List<MtdDFontedati> findByCriteria(java.util.Map<String, Object> params);
	public List<MtdDFontedati> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<MtdDFontedati> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(MtdDFontedati bean);

	public void update(MtdDFontedati bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idFontedati);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<MtdDFontedati> getRowMapper();
}
