/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.MtdRParolachiaveMtd;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * MtdRParolachiaveMtd DAO interface
 * 
 * @author Telosys Tools
 */
public interface MtdRParolachiaveMtdDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idMetadato
	 * @param idParolaChiave
	 * @return the bean found or null if not found 
	 */
	public MtdRParolachiaveMtd findByPK(Integer idMetadato, Integer idParolaChiave);

	public List<MtdRParolachiaveMtd> findAll();
	
	public List<MtdRParolachiaveMtd> findByCriteria(java.util.Map<String, Object> params);
	public List<MtdRParolachiaveMtd> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<MtdRParolachiaveMtd> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(MtdRParolachiaveMtd bean);

	public void update(MtdRParolachiaveMtd bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idMetadato, Integer idParolaChiave);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<MtdRParolachiaveMtd> getRowMapper();
}
