/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.MtdTFunzione;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * MtdTFunzione DAO interface
 * 
 * @author Telosys Tools
 */
public interface MtdTFunzioneDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idFunzione
	 * @return the bean found or null if not found 
	 */
	public MtdTFunzione findByPK(Integer idFunzione);

	public List<MtdTFunzione> findAll();
	
	public List<MtdTFunzione> findByCriteria(java.util.Map<String, Object> params);
	public List<MtdTFunzione> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<MtdTFunzione> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(MtdTFunzione bean);

	public void update(MtdTFunzione bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idFunzione);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<MtdTFunzione> getRowMapper();
}
