/*
 * Created on 18 nov 2016 ( Time 17:08:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.MtdTMtdPlus;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * MtdTMtdPlus DAO interface
 * 
 * @author Telosys Tools
 */
public interface MtdTMtdPlusDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idMetadato
	 * @return the bean found or null if not found 
	 */
	public MtdTMtdPlus findByPK(Integer idMetadato);

	public List<MtdTMtdPlus> findAll();
	
	public List<MtdTMtdPlus> findByCriteria(java.util.Map<String, Object> params);
	public List<MtdTMtdPlus> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<MtdTMtdPlus> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(MtdTMtdPlus bean);

	public void update(MtdTMtdPlus bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idMetadato);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<MtdTMtdPlus> getRowMapper();
}
