/*
 * Created on 18 nov 2016 ( Time 17:08:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.MtdTStoricoMtdCsw;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * MtdTStoricoMtdCsw DAO interface
 * 
 * @author Telosys Tools
 */
public interface MtdTStoricoMtdCswDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idStoricoMetadato
	 * @return the bean found or null if not found 
	 */
	public MtdTStoricoMtdCsw findByPK(Integer idStoricoMetadato);

	public List<MtdTStoricoMtdCsw> findAll();
	
	public List<MtdTStoricoMtdCsw> findByCriteria(java.util.Map<String, Object> params);
	public List<MtdTStoricoMtdCsw> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<MtdTStoricoMtdCsw> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(MtdTStoricoMtdCsw bean);

	public void update(MtdTStoricoMtdCsw bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idStoricoMetadato);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<MtdTStoricoMtdCsw> getRowMapper();
}
