/*
 * Created on 18 nov 2016 ( Time 17:08:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dao;

import it.csi.sira.backend.metadata.integration.dto.MtdTCategoriaAppl;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;




/**
 * MtdTCategoriaAppl DAO interface
 * 
 * @author Telosys Tools
 */
public interface MtdTCategoriaApplDAO {

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param idCategoriaAppl
	 * @return the bean found or null if not found 
	 */
	public MtdTCategoriaAppl findByPK(Integer idCategoriaAppl);

	public List<MtdTCategoriaAppl> findAll();
	
	public List<MtdTCategoriaAppl> findByCriteria(java.util.Map<String, Object> params);
	public List<MtdTCategoriaAppl> findByCriteria(MapSqlParameterSource params);
	
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, Map<String, Object> params);
	public <V> List<V> findByGenericCriteria(String query, RowMapper<V>  rowMapper, MapSqlParameterSource params);
	public List<MtdTCategoriaAppl> findByGenericCriteria(String query, MapSqlParameterSource params);
	
	public void insert(MtdTCategoriaAppl bean);

	public void update(MtdTCategoriaAppl bean);
	
	public void update(String sql, Map<String, Object> param);

	public int deleteByPK(Integer idCategoriaAppl);
	
	public int delete(String query, Map<String, Object> params);
	public int delete(String query, MapSqlParameterSource params);

	public boolean exist(Map<String, Object> params);

    public RowMapper<MtdTCategoriaAppl> getRowMapper();
}
