/*
 * Created on 18 nov 2016 ( Time 17:08:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.integration.dto;

import java.io.Serializable;


/**
 * Java bean for 'MtdDFontedati' entity
 * 
 * @author Telosys Tools
 *
 */
public class MtdDFontedati implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id_datasource int4 
    private Integer idFontedati;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : fk_standard_expos int4 
    private Integer fkStandardEspos;

    // DB : des_datasource varchar 
    private String desFontedati;

    // DB : url_prefix_metadata varchar 
    private String urlPrefissoMetadato;

    // DB : url_service varchar 
    private String urlServizio;

    // DB : fl_active varchar 
    private String flAttiva;

    // DB : prefix_datasource varchar 
    private String prefissoFontedati;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdFontedati( Integer idFontedati ) {
        this.idFontedati = idFontedati ;
    }

    public Integer getIdFontedati() {
        return this.idFontedati;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setFkStandardEspos( Integer fkStandardEspos ) {
        this.fkStandardEspos = fkStandardEspos;
    }
    public Integer getFkStandardEspos() {
        return this.fkStandardEspos;
    }

    public void setDesFontedati( String desFontedati ) {
        this.desFontedati = desFontedati;
    }
    public String getDesFontedati() {
        return this.desFontedati;
    }

    public void setUrlPrefissoMetadato( String urlPrefissoMetadato ) {
        this.urlPrefissoMetadato = urlPrefissoMetadato;
    }
    public String getUrlPrefissoMetadato() {
        return this.urlPrefissoMetadato;
    }

    public void setUrlServizio( String urlServizio ) {
        this.urlServizio = urlServizio;
    }
    public String getUrlServizio() {
        return this.urlServizio;
    }

    public void setFlAttiva( String flAttiva ) {
        this.flAttiva = flAttiva;
    }
    public String getFlAttiva() {
        return this.flAttiva;
    }

    public void setPrefissoFontedati( String prefissoFontedati ) {
        this.prefissoFontedati = prefissoFontedati;
    }
    public String getPrefissoFontedati() {
        return this.prefissoFontedati;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idFontedati);
        sb.append("|");
        sb.append(fkStandardEspos);
        sb.append("|");
        sb.append(desFontedati);
        sb.append("|");
        sb.append(urlPrefissoMetadato);
        sb.append("|");
        sb.append(urlServizio);
        sb.append("|");
        sb.append(flAttiva);
        sb.append("|");
        sb.append(prefissoFontedati);
        return sb.toString(); 
    } 


}
