/*
 * Created on 18 nov 2016 ( Time 17:08:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package it.csi.sira.backend.metadata.utils;

import it.csi.sira.backend.metadata.integration.dao.MtdDFontedatiDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdDLinguaDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdDStandardEsposDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdDTipoCategoriaDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdDTipoFunzioneDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdDTipoOggettoDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdRCategLinguaDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdRCategappCategoriDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdRCategoriaMtdDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdRParolachiaveMtdDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTCategoriaDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTCategoriaApplDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTDettlogDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTFunzioneDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTLogDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTMetadatoDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTMtdCswDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTMtdPlusDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTParolaChiaveDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTStoricoFunzioneDAO;
import it.csi.sira.backend.metadata.integration.dao.MtdTStoricoMtdCswDAO;

public class DAOManager 
{

 private MtdDFontedatiDAO mtdDFontedatiDAO;
 private MtdDLinguaDAO mtdDLinguaDAO;
 private MtdDStandardEsposDAO mtdDStandardEsposDAO;
 private MtdDTipoCategoriaDAO mtdDTipoCategoriaDAO;
 private MtdDTipoFunzioneDAO mtdDTipoFunzioneDAO;
 private MtdDTipoOggettoDAO mtdDTipoOggettoDAO;
 private MtdRCategLinguaDAO mtdRCategLinguaDAO;
 private MtdRCategappCategoriDAO mtdRCategappCategoriDAO;
 private MtdRCategoriaMtdDAO mtdRCategoriaMtdDAO;
 private MtdRParolachiaveMtdDAO mtdRParolachiaveMtdDAO;
 private MtdTCategoriaDAO mtdTCategoriaDAO;
 private MtdTCategoriaApplDAO mtdTCategoriaApplDAO;
 private MtdTDettlogDAO mtdTDettlogDAO;
 private MtdTFunzioneDAO mtdTFunzioneDAO;
 private MtdTLogDAO mtdTLogDAO;
 private MtdTMetadatoDAO mtdTMetadatoDAO;
 private MtdTMtdCswDAO mtdTMtdCswDAO;
 private MtdTMtdPlusDAO mtdTMtdPlusDAO;
 private MtdTParolaChiaveDAO mtdTParolaChiaveDAO;
 private MtdTStoricoFunzioneDAO mtdTStoricoFunzioneDAO;
 private MtdTStoricoMtdCswDAO mtdTStoricoMtdCswDAO;

 public void setMtdDFontedatiDAO(MtdDFontedatiDAO mtdDFontedatiDAO)
 {
  this.mtdDFontedatiDAO = mtdDFontedatiDAO;
 }

 public MtdDFontedatiDAO getMtdDFontedatiDAO()
 {
  return this.mtdDFontedatiDAO;
 }

 public void setMtdDLinguaDAO(MtdDLinguaDAO mtdDLinguaDAO)
 {
  this.mtdDLinguaDAO = mtdDLinguaDAO;
 }

 public MtdDLinguaDAO getMtdDLinguaDAO()
 {
  return this.mtdDLinguaDAO;
 }

 public void setMtdDStandardEsposDAO(MtdDStandardEsposDAO mtdDStandardEsposDAO)
 {
  this.mtdDStandardEsposDAO = mtdDStandardEsposDAO;
 }

 public MtdDStandardEsposDAO getMtdDStandardEsposDAO()
 {
  return this.mtdDStandardEsposDAO;
 }

 public void setMtdDTipoCategoriaDAO(MtdDTipoCategoriaDAO mtdDTipoCategoriaDAO)
 {
  this.mtdDTipoCategoriaDAO = mtdDTipoCategoriaDAO;
 }

 public MtdDTipoCategoriaDAO getMtdDTipoCategoriaDAO()
 {
  return this.mtdDTipoCategoriaDAO;
 }

 public void setMtdDTipoFunzioneDAO(MtdDTipoFunzioneDAO mtdDTipoFunzioneDAO)
 {
  this.mtdDTipoFunzioneDAO = mtdDTipoFunzioneDAO;
 }

 public MtdDTipoFunzioneDAO getMtdDTipoFunzioneDAO()
 {
  return this.mtdDTipoFunzioneDAO;
 }

 public void setMtdDTipoOggettoDAO(MtdDTipoOggettoDAO mtdDTipoOggettoDAO)
 {
  this.mtdDTipoOggettoDAO = mtdDTipoOggettoDAO;
 }

 public MtdDTipoOggettoDAO getMtdDTipoOggettoDAO()
 {
  return this.mtdDTipoOggettoDAO;
 }

 public void setMtdRCategLinguaDAO(MtdRCategLinguaDAO mtdRCategLinguaDAO)
 {
  this.mtdRCategLinguaDAO = mtdRCategLinguaDAO;
 }

 public MtdRCategLinguaDAO getMtdRCategLinguaDAO()
 {
  return this.mtdRCategLinguaDAO;
 }

 public void setMtdRCategappCategoriDAO(MtdRCategappCategoriDAO mtdRCategappCategoriDAO)
 {
  this.mtdRCategappCategoriDAO = mtdRCategappCategoriDAO;
 }

 public MtdRCategappCategoriDAO getMtdRCategappCategoriDAO()
 {
  return this.mtdRCategappCategoriDAO;
 }

 public void setMtdRCategoriaMtdDAO(MtdRCategoriaMtdDAO mtdRCategoriaMtdDAO)
 {
  this.mtdRCategoriaMtdDAO = mtdRCategoriaMtdDAO;
 }

 public MtdRCategoriaMtdDAO getMtdRCategoriaMtdDAO()
 {
  return this.mtdRCategoriaMtdDAO;
 }

 public void setMtdRParolachiaveMtdDAO(MtdRParolachiaveMtdDAO mtdRParolachiaveMtdDAO)
 {
  this.mtdRParolachiaveMtdDAO = mtdRParolachiaveMtdDAO;
 }

 public MtdRParolachiaveMtdDAO getMtdRParolachiaveMtdDAO()
 {
  return this.mtdRParolachiaveMtdDAO;
 }

 public void setMtdTCategoriaDAO(MtdTCategoriaDAO mtdTCategoriaDAO)
 {
  this.mtdTCategoriaDAO = mtdTCategoriaDAO;
 }

 public MtdTCategoriaDAO getMtdTCategoriaDAO()
 {
  return this.mtdTCategoriaDAO;
 }

 public void setMtdTCategoriaApplDAO(MtdTCategoriaApplDAO mtdTCategoriaApplDAO)
 {
  this.mtdTCategoriaApplDAO = mtdTCategoriaApplDAO;
 }

 public MtdTCategoriaApplDAO getMtdTCategoriaApplDAO()
 {
  return this.mtdTCategoriaApplDAO;
 }

 public void setMtdTDettlogDAO(MtdTDettlogDAO mtdTDettlogDAO)
 {
  this.mtdTDettlogDAO = mtdTDettlogDAO;
 }

 public MtdTDettlogDAO getMtdTDettlogDAO()
 {
  return this.mtdTDettlogDAO;
 }

 public void setMtdTFunzioneDAO(MtdTFunzioneDAO mtdTFunzioneDAO)
 {
  this.mtdTFunzioneDAO = mtdTFunzioneDAO;
 }

 public MtdTFunzioneDAO getMtdTFunzioneDAO()
 {
  return this.mtdTFunzioneDAO;
 }

 public void setMtdTLogDAO(MtdTLogDAO mtdTLogDAO)
 {
  this.mtdTLogDAO = mtdTLogDAO;
 }

 public MtdTLogDAO getMtdTLogDAO()
 {
  return this.mtdTLogDAO;
 }

 public void setMtdTMetadatoDAO(MtdTMetadatoDAO mtdTMetadatoDAO)
 {
  this.mtdTMetadatoDAO = mtdTMetadatoDAO;
 }

 public MtdTMetadatoDAO getMtdTMetadatoDAO()
 {
  return this.mtdTMetadatoDAO;
 }

 public void setMtdTMtdCswDAO(MtdTMtdCswDAO mtdTMtdCswDAO)
 {
  this.mtdTMtdCswDAO = mtdTMtdCswDAO;
 }

 public MtdTMtdCswDAO getMtdTMtdCswDAO()
 {
  return this.mtdTMtdCswDAO;
 }

 public void setMtdTMtdPlusDAO(MtdTMtdPlusDAO mtdTMtdPlusDAO)
 {
  this.mtdTMtdPlusDAO = mtdTMtdPlusDAO;
 }

 public MtdTMtdPlusDAO getMtdTMtdPlusDAO()
 {
  return this.mtdTMtdPlusDAO;
 }

 public void setMtdTParolaChiaveDAO(MtdTParolaChiaveDAO mtdTParolaChiaveDAO)
 {
  this.mtdTParolaChiaveDAO = mtdTParolaChiaveDAO;
 }

 public MtdTParolaChiaveDAO getMtdTParolaChiaveDAO()
 {
  return this.mtdTParolaChiaveDAO;
 }

 public void setMtdTStoricoFunzioneDAO(MtdTStoricoFunzioneDAO mtdTStoricoFunzioneDAO)
 {
  this.mtdTStoricoFunzioneDAO = mtdTStoricoFunzioneDAO;
 }

 public MtdTStoricoFunzioneDAO getMtdTStoricoFunzioneDAO()
 {
  return this.mtdTStoricoFunzioneDAO;
 }

 public void setMtdTStoricoMtdCswDAO(MtdTStoricoMtdCswDAO mtdTStoricoMtdCswDAO)
 {
  this.mtdTStoricoMtdCswDAO = mtdTStoricoMtdCswDAO;
 }

 public MtdTStoricoMtdCswDAO getMtdTStoricoMtdCswDAO()
 {
  return this.mtdTStoricoMtdCswDAO;
 }

}
